[package]
name = "aoc2024"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
itertools = "0.13.0"

[[bin]]
name = "day01"
path = "src/day01/bin.rs"

[[bin]]
name = "day02"
path = "src/day02/bin.rs"

[[bin]]
name = "day03"
path = "src/day03/bin.rs"
