[package]
name = "aoc2020"
version = "0.1.0"
edition = "2021"

[lib]
name = "aoc"
path = "src/lib.rs"

[[bin]]
name = "day1"
path = "src/bin/day1.rs"

[[bin]]
name = "day2"
path = "src/bin/day2.rs"

[dependencies]
anyhow = "1.0.51"
itertools = "0.10.1"